package com.qf.entity;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "t_goods")
public class Goods implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbggenerated Tue Aug 27 15:31:07 CST 2019
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.gname
     *
     * @mbggenerated Tue Aug 27 15:31:07 CST 2019
     */
    private String gname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.gdesc
     *
     * @mbggenerated Tue Aug 27 15:31:07 CST 2019
     */
    private String gdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.gprice
     *
     * @mbggenerated Tue Aug 27 15:31:07 CST 2019
     */
    private Double gprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.gtype
     *
     * @mbggenerated Tue Aug 27 15:31:07 CST 2019
     */
    private Integer gtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.gstock
     *
     * @mbggenerated Tue Aug 27 15:31:07 CST 2019
     */
    private Integer gstock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.gpic
     *
     * @mbggenerated Tue Aug 27 15:31:07 CST 2019
     */
    private String gpic;

}